/**
 * Seed script — generates ~300 simulated telemetry records
 * across 3 experiments with realistic, gradually varying values.
 *
 * IMPORTANT: All data generated by this script is SIMULATED.
 * It is for software development and testing purposes only.
 * Do not present simulated values as real experimental results.
 *
 * Usage: node scripts/seedData.js
 */

require('dotenv').config();
const mongoose = require('mongoose');
const Telemetry = require('../src/models/Telemetry');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/windturbine';

// Experiment definitions
const experiments = [
    {
        experimentId: 'EXP-001',
        pitchAngle: 0,
        windSpeedRange: [2, 4],     // m/s
        voltageBase: 4.0,           // V base at low wind
        currentBase: 0.5,           // A base at low wind
        recordCount: 100,
        description: 'Pitch 0° — Low wind speed range',
    },
    {
        experimentId: 'EXP-002',
        pitchAngle: 4,
        windSpeedRange: [3, 6],
        voltageBase: 6.0,
        currentBase: 0.8,
        recordCount: 100,
        description: 'Pitch 4° — Medium wind speed range',
    },
    {
        experimentId: 'EXP-003',
        pitchAngle: 20,
        windSpeedRange: [5, 8],
        voltageBase: 5.0,
        currentBase: 0.6,
        recordCount: 100,
        description: 'Pitch 20° — High wind speed range',
    },
];

/**
 * Generate a value that gradually varies from the previous value.
 * Simulates sensor readings that change smoothly over time.
 */
function gradualValue(previous, min, max, maxStep) {
    const step = (Math.random() - 0.5) * 2 * maxStep;
    let next = previous + step;
    next = Math.max(min, Math.min(max, next));
    return parseFloat(next.toFixed(3));
}

/**
 * Generate records for a single experiment.
 */
function generateExperiment(experiment) {
    const records = [];
    const {
        experimentId,
        pitchAngle,
        windSpeedRange,
        voltageBase,
        currentBase,
        recordCount,
    } = experiment;

    // Start timestamp: 1 hour ago, progressing forward
    const startTime = new Date(Date.now() - recordCount * 5000); // 5s intervals

    // Initialize starting values at midpoint of range
    let windSpeed = (windSpeedRange[0] + windSpeedRange[1]) / 2;
    let voltage = voltageBase;
    let current = currentBase;
    let stepperPosition = pitchAngle * 50; // rough mapping: 50 steps per degree

    for (let i = 0; i < recordCount; i++) {
        // Gradually vary wind speed within range
        windSpeed = gradualValue(
            windSpeed,
            windSpeedRange[0],
            windSpeedRange[1],
            0.3 // max change per step
        );

        // Voltage correlates with wind speed — higher wind → more voltage
        const windFactor = (windSpeed - windSpeedRange[0]) / (windSpeedRange[1] - windSpeedRange[0]);
        const targetVoltage = voltageBase + windFactor * 4 + (Math.random() - 0.5) * 0.3;
        voltage = gradualValue(voltage, voltageBase * 0.5, voltageBase + 6, 0.2);
        voltage = voltage * 0.7 + targetVoltage * 0.3; // blend towards target
        voltage = parseFloat(Math.max(0.1, voltage).toFixed(3));

        // Current correlates with wind speed
        const targetCurrent = currentBase + windFactor * 1.5 + (Math.random() - 0.5) * 0.1;
        current = gradualValue(current, currentBase * 0.3, currentBase + 2, 0.08);
        current = current * 0.7 + targetCurrent * 0.3;
        current = parseFloat(Math.max(0.01, current).toFixed(3));

        // Power is calculated server-side (voltage × current)
        const power = parseFloat((voltage * current).toFixed(4));

        // Stepper position has minor drift
        stepperPosition = gradualValue(stepperPosition, stepperPosition - 5, stepperPosition + 5, 1);
        stepperPosition = Math.round(stepperPosition);

        const timestamp = new Date(startTime.getTime() + i * 5000); // 5-second intervals

        records.push({
            experimentId,
            source: 'simulator',
            timestamp,
            windSpeed,
            pitchAngle,
            stepperPosition,
            voltage,
            current,
            power,
        });
    }

    return records;
}

async function seed() {
    try {
        console.log('Connecting to MongoDB...');
        await mongoose.connect(MONGO_URI);
        console.log('MongoDB connected');

        // Clear existing simulated data
        const deleted = await Telemetry.deleteMany({ source: 'simulator' });
        console.log(`Cleared ${deleted.deletedCount} existing simulated records`);

        let totalInserted = 0;

        for (const experiment of experiments) {
            console.log(`\nGenerating: ${experiment.description}`);
            const records = generateExperiment(experiment);
            await Telemetry.insertMany(records);
            console.log(`  Inserted ${records.length} records for ${experiment.experimentId}`);
            totalInserted += records.length;
        }

        console.log(`\n========================================`);
        console.log(`SEED COMPLETE`);
        console.log(`Total records inserted: ${totalInserted}`);
        console.log(`Source: simulator (SIMULATED DATA)`);
        console.log(`========================================`);
        console.log(`\nExperiments:`);
        for (const exp of experiments) {
            console.log(`  ${exp.experimentId}: pitch=${exp.pitchAngle}°, wind=${exp.windSpeedRange[0]}-${exp.windSpeedRange[1]} m/s`);
        }

        await mongoose.connection.close();
        console.log('\nMongoDB connection closed');
        process.exit(0);
    } catch (error) {
        console.error('Seed error:', error.message);
        process.exit(1);
    }
}

seed();
